openapi: 3.0.3
info:
  title: Users Demmo - OpenAPI 3.0
  description: |
    Users Demo is a project to test springboot framework
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: users
    description: Operations about users
paths:
  /users:
    post:
      tags:
        - user
      summary: Create user
      description: This can only be done by the logged in user.
      operationId: createUser
      requestBody:
        description: Created user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '200':
          description: Successful operation
        '400':
          description: |
            Bad Request 
            - Missing required attribute
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
              examples:
                MissingRequiredAttribute:
                  $ref: '#/components/examples/MissingRequiredAttributeExample'


components:
  schemas:
    CreateUserRequest:
      type: object
      required:
        - username
        - email
        - password
        - phone
      properties:
        id:
          type: integer
          format: int64
          example: 10
        username:
          type: string
          example: theUser
        password:
          type: string
          example: 1234
        email:
          type: string
          example: john@email.com
        phone:
          type: string
          example: '12345'
    BadRequest:
      type: object
      required:
        - username
        - email
        - phone
      properties:
        code:
          type: string
          example: MISSING_REQUIRED_ARGUMENT
        reason:
          type: string
          example: missing arguments
  examples:
    MissingRequiredAttributeExample:
      value:
        code: users.MISSING_REQUIRED_ARGUMENT
        reason: missing required %S attribute

